import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "FFFFFF",
    paddingLeft: 15,
    paddingRight: 15,
  },
  inputContent: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    padding: 0,
    gap: 10,
    width: "100%",
    marginBottom: 25,
  },
  label: {
    fontSize: 12,
    fontWeight: 400,
    lineHeight: 15,
    color: "#374857",
  },
  input: {
    width: "100%",
    height: 60,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 20,
    paddingLeft: 14,
    paddingRight: 14,
    gap: 14,
    backgroundColor: "#E8E7E7",
    borderRadius: 10,
  },
  title: {
    // fontFamily: "Inter",
    fontSize: 32,
    fontWeight: 700,
    lineHeight: 39,
    color: "#374857",
    marginBottom: 70,
  },
  checkContent: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    gap: 8,
    marginBottom: 25,
  },
  checkButton: {},
  buttonContent: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 50,
  },
  buttonPrimary: {
    width: 180,
    height: 60,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 20,
    paddingLeft: 14,
    paddingRight: 14,
    gap: 8,
    backgroundColor: "#5E548E",
    borderRadius: 10,
  },
  buttonSecond: {
    width: 180,
    height: 60,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 20,
    paddingLeft: 14,
    paddingRight: 14,
    gap: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#5E548E",
  },
  buttonTitlePrimary: {
    fontSize: 18,
    fontWeight: 700,
    lineHeight: 22,
    color: "#ffffff",
  },
  buttonTitleSecond: {
    fontSize: 18,
    fontWeight: 700,
    lineHeight: 22,
    color: "#5E548E",
  },
  logo: {
    width: 350,
    height: 350,
    marginBottom: 70,
  },
});
